#!/usr/bin/env python3
"""
Regenerate ring_vm_computedgoto() in ringvm/src/vm.c from the switch in
ring_vm_execute() and the opcode enum in ringvm/include/codegen.h.

RINGSCRIPT PATCH (5) maintenance, and part of the upstream offer in
docs/UPSTREAM_CASE.md item 4: the function is a mechanical transform of
the switch — one label per opcode, bodies identical, label table in enum
order — and MUST be regenerated whenever the opcode enum or a case body
changes, because a stale label table dispatches the wrong opcode.

Usage:  python tools/regen-computedgoto.py        (from the repo root)
Idempotent: running it twice changes nothing.
"""
import io
import re
import sys
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VM_C = os.path.join(ROOT, "ringvm", "src", "vm.c")
CODEGEN_H = os.path.join(ROOT, "ringvm", "include", "codegen.h")

BEGIN = "#ifdef RING_VM_COMPUTEDGOTO"


def main():
    h = io.open(CODEGEN_H, encoding="utf-8", newline="").read()
    em = re.search(r"typedef enum\s*\w*\s*\{(.*?)\}", h, re.S)
    enum = re.findall(r"\b(ICO_\w+)\b", em.group(1))

    raw = io.open(VM_C, encoding="utf-8", newline="").read()
    nl = "\r\n" if "\r\n" in raw else "\n"
    body_src = raw.replace("\r\n", "\n")

    # Strip a previously generated block (idempotence). The vendor has its
    # OWN "#ifdef RING_VM_COMPUTEDGOTO" inside ring_vm_mainloop — matching
    # the first ifdef once truncated the whole back half of the file. The
    # generated block is identified by its unique marker comment instead.
    marker = "** RINGSCRIPT PATCH (5):"
    mk = body_src.find(marker)
    if mk >= 0:
        gen_at = body_src.rfind("\n" + BEGIN, 0, mk)
        if gen_at < 0:
            raise SystemExit("marker found but its #ifdef line was not — refusing to touch vm.c")
        end = body_src.find("#endif", mk)
        if end < 0:
            raise SystemExit("generated block has no #endif — refusing to touch vm.c")
        body_src = body_src[:gen_at].rstrip("\n") + "\n" + body_src[end + len("#endif"):].lstrip("\n")
    if "void ring_vm_execute(VM *pVM) {" not in body_src:
        raise SystemExit("ring_vm_execute missing after strip — refusing to touch vm.c")

    # isolate ring_vm_execute's switch
    i = body_src.find("void ring_vm_execute(VM *pVM) {")
    depth = 0
    j = i
    while True:
        c = body_src[j]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                break
        j += 1
    execute = body_src[i : j + 1]

    cases = {}
    for m in re.finditer(r"case (ICO_\w+):\n(.*?)\n\t\tbreak;", execute, re.S):
        cases[m.group(1)] = m.group(2)
    missing = [e for e in enum if e not in cases]
    print("opcodes: %d   case bodies: %d   fallthrough: %s" % (len(enum), len(cases), missing))
    if len(cases) < 100:
        raise SystemExit("captured only %d case bodies — refusing to write a broken dispatch" % len(cases))

    out = []
    out.append("")
    out.append(BEGIN)
    out.append("/*")
    out.append("** RINGSCRIPT PATCH (5): the computed-goto dispatch loop the vendor")
    out.append("** scaffolded — vm.h declares ring_vm_computedgoto() under this same")
    out.append("** guard, ring_vm_mainloop() calls it, and the comment there says it")
    out.append('** "must be written if RING_VM_COMPUTEDGOTO is enabled". This writes it.')
    out.append("**")
    out.append("** GENERATED by tools/regen-computedgoto.py from ring_vm_execute()'s")
    out.append("** switch: one label per opcode, bodies identical, label table in")
    out.append("** codegen.h enum order (opcodes with no case there fall through, as")
    out.append("** the switch does). The win in wasm is not the goto itself (clang")
    out.append("** lowers both this and a dense switch to br_table) — it is that")
    out.append("** fetch, dispatch and the stack check live in ONE loop with no")
    out.append("** function call per instruction. Behavior is held identical to the")
    out.append("** fetch loop by the oracle battery (~850 programs byte-exact vs")
    out.append("** native ring.exe).")
    out.append("**")
    out.append("** If codegen.h's opcode enum or a case body changes, RERUN THE")
    out.append("** GENERATOR — a stale label table dispatches the wrong opcode.")
    out.append("** Enabled with -DRING_VM_COMPUTEDGOTO (build.zig).")
    out.append("*/")
    out.append("void ring_vm_computedgoto(VM *pVM) {")
    out.append("\tstatic const void *aLabels[] = {")
    for k in range(0, len(enum), 4):
        row = ", ".join("&&rs_cg_%s" % e for e in enum[k : k + 4])
        out.append("\t    " + row + ("," if k + 4 < len(enum) else ""))
    out.append("\t};")
    out.append("rs_cg_fetch:")
    out.append("\tpVM->pByteCodeIR = pVM->pByteCode + pVM->nPC - 1;")
    out.append("\tpVM->nOPCode = RING_VM_IR_OPCODE;")
    out.append("\tpVM->nPC++;")
    out.append("\tgoto *aLabels[pVM->nOPCode];")
    out.append("rs_cg_check:")
    out.append("\tif (pVM->nSP > RING_VM_STACK_CHECKOVERFLOW) {")
    out.append("\t\tring_vm_error(pVM, RING_VM_ERROR_STACKOVERFLOW);")
    out.append("\t}")
    out.append("\tif (pVM->nPC <= RING_VM_INSTRUCTIONSCOUNT) {")
    out.append("\t\tgoto rs_cg_fetch;")
    out.append("\t}")
    out.append("\treturn;")
    for e in enum:
        out.append("rs_cg_%s:" % e)
        if e in cases:
            out.append(cases[e])
        out.append("\tgoto rs_cg_check;")
    out.append("}")
    out.append("#endif")

    result = body_src + "\n".join(out) + "\n"
    io.open(VM_C, "w", encoding="utf-8", newline="").write(result.replace("\n", nl) if nl == "\r\n" else result)
    print("regenerated into", VM_C)


if __name__ == "__main__":
    sys.exit(main())
